baseURL = 'https://vuong.work/public-notes/'
languageCode = 'en-us'
title = 'Notes by Vu'
theme = 'hugo-book'
enableGitInfo = true

[params]
    # (Optional, default light) Sets color theme: light, dark or auto.
    # Theme 'auto' switches between dark and light modes based on browser/os preferences
    BookTheme = 'auto'
